# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsocialfeed', '0002_auto_20161005_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialfeedconfiguration',
            name='source',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=100, verbose_name='Feed source'),
        ),
    ]
